### PR TITLE
F/code coverage support

### PR DESCRIPTION
**Pull request by beporter**
Try simplifying the build system by depending on FriendsOfCake/travis.

This should also give us Coveralls coverage pretty much for free.

### CODE REVIEW

**Comment by beporter** [comment]
This doesn't quite solve #6, which has the intent of **failing** a Travis build if coverage is sub-standard, not just _reporting_ what the coverage is.

**Comment by beporter** [comment]
Which introduces a question: If the build fails, the "after" script to update the coverage on Coveralls won't fire. This has the nice effect of ensuring that our reported coverage is always green since only build that maintain that coverage will update the badge (to still be green of course), but might be seen as defeating the purpose of reporting the "true" coverage of the package.

**Comment by jtyost2** [comment]
Up to failing on real reasons inside the Builds rather than dumb mistakes. Now failing due to re-declaring classes in the builds.

Code sniffer is also using Loadsys' standard and failing due to that.

**Comment by beporter** [comment]
Well the codesniffer at least is legit. I want to be using ours (but our codesniffer needs updating/repairs too. Got your yak clippers handy?)

**Comment by jtyost2** [comment]
Coveralls has the ability to mark a build as a failure if coverage drops below a certain rate.
screen shot 2015-04-01 at 5 33 00 pm

**Pull request merged**
