### PR TITLE
F/serializers errors

### PR DESCRIPTION
**Pull request by jtyost2**
Integrates SerializersErrors as part of this plugin.

### CODE REVIEW

**Comment by jtyost2** [comment]
Assigning to @beporter for review.

**Comment by beporter** [comment]
I really worry that removing the getter methods was a mis-step. It closes us off from being able to _generate_ values based on what we know about the current request. `$exception->url` retrieves the property...if its set already, but `$exception->getUrl()` could have looked up the current URL from the request object on its own even if it was empty.

**Comment by beporter** [comment]
It would have even been possible to avoid all of the tiny boilerplate methods by using `__call()` at the lowest levels to match `get[Property]()` style calls, but we would have had that interface defined at the lowest possible levels then.

**Comment by jtyost2** [comment]
Two points:

1. I can in fact get the current url from the ErrorRenderer Class as seen here: https://github.com/loadsys/CakePHP-Serializers-Errors/blob/master/Lib/Error/SerializerExceptionRenderer.php#L105

2. http://jsonapi.org/format/#errors The url in JSON API Errors is a url to more information, not the url where the error occurred.

**Comment by beporter** [comment]
You're missing my point. We can't (easily) hook into the return value for properties accessed directly. It would have been trivial to do so for getter methods. We're now explicitly encourage package consumers to access those properties directly, which will make transitioning to getters that much harder in the future.

**Comment by jtyost2** [comment]
I'm open to the idea of it, but I'm not really convinced of a real scenario of this need existing.

What's the scenario where we (or someone else) needs to access or modify the return properties, but can't do so in the constructor or when they actually set said property?

**Comment by beporter** [comment]
Using the constructor is a fair point, but then it becomes a separation of concerns thing. How is it the constructor's job to decorate _all_ of the values for use? That's what individual getter's are for, really. That's why Cake 3 switched to entities where this is the "normal" way to retrieve a value from a record, after all. Seems like a good pattern to follow, is all I'm saying.

**Pull request merged**
